# Generated by Django 4.2.2 on 2023-06-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth',
            options={'ordering': ['name'], 'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
    ]
